# coding=utf-8

import unittest
from Base.browser_engine import BrowserEngine
from PageObjects.oa_homepage import LoginHomePage, IndexHomePage, RecvPage, LSDToDoHomePage, ZZBToDoHomePage, YLToDoHomePage
from Base.base_page import BasePage
import time
from Base.retry_func import retry_method, retry_class


@retry_class(3)
class TestOaReceiveDocument(unittest.TestCase, BasePage):

    def setUp(self):
        browser = BrowserEngine(self)
        self.driver = browser.open_browser(self)

    def tearDown(self):
        self.driver.quit()

    def test_recv_process(self):
        home_page = LoginHomePage(self.driver)
        index_page = IndexHomePage(self.driver)
        recv_page = RecvPage(self.driver)
        to_do_page_lsd = LSDToDoHomePage(self.driver)
        to_do_page_zzb = ZZBToDoHomePage(self.driver)
        todo_page_yl = YLToDoHomePage(self.driver)
        # 创建工单 - 杨磊创建工单传递给刘绍东
        home_page.input_user("jtyanglei")
        home_page.input_passwd("123456")
        home_page.submit_login()
        index_page.click_recv_send_manager()
        index_page.click_recv_manager()
        recv_page.switch_to_recv_iframe()
        recv_page.send_keys_input_recv_comp('ZHR-自动化测试 - 来文单位')
        recv_page.send_keys_input_recv_sort('ZHR-自动化测试 - 文件编号')
        recv_page.send_keys_input_recv_num('10')
        recv_page.send_keys_input_file_name('ZHR-自动化测试 - 文件名称')
        recv_page.send_keys_input_comment('ZHR-自动化测试 - 杨磊 - 拟办意见')
        recv_page.click_button_signature()
        recv_page.click_button_save()
        recv_page.switch_default_frame()
        recv_page.click_button_saved_known()
        recv_page.switch_to_recv_iframe()
        recv_page.click_button_pass()
        recv_page.switch_default_frame()
        recv_page.click_button_pass_known()
        recv_page.switch_default_frame()
        recv_page.switch_to_choose_member_frame()
        recv_page.click_liushaodong()
        recv_page.click_button_choose_member_ok()
        recv_page.switch_default_frame()
        recv_page.click_button_pass_again_ok()
        time.sleep(5)
        recv_page.get_pass_result_text()
        recv_page.click_button_pass_again_ok_known()

        # 退出登录 登陆刘绍东
        index_page.hover_user_info()
        index_page.click_button_quit()
        home_page.input_user("jtliushaodong")
        home_page.input_passwd("123456")
        home_page.submit_login()

        # 主任审核 - 刘绍东处理工单传递给张振博
        index_page.hover_user_info()
        index_page.click_to_do()
        to_do_page_lsd.click_max_to_do_frame()
        to_do_page_lsd.switch_to_to_do_frame()
        to_do_page_lsd.click_button_to_do_solve()
        to_do_page_lsd.switch_default_frame()
        to_do_page_lsd.click_button_max_frame_task_detail()
        to_do_page_lsd.switch_frame_task_deal()
        to_do_page_lsd.switch_frame_task_detail()
        # to_do_page_lsd.send_keys_input_comment('ZHR-自动化测试 - 刘绍东 - 拟办意见')
        # to_do_page_lsd.click_button_signature()
        to_do_page_lsd.click_button_save()
        to_do_page_lsd.switch_default_frame()
        to_do_page_lsd.click_button_saved_known()
        to_do_page_lsd.switch_frame_task_deal()
        to_do_page_lsd.switch_frame_task_detail()
        to_do_page_lsd.click_button_pass()
        to_do_page_lsd.switch_default_frame()
        to_do_page_lsd.switch_to_choose_member_frame()
        to_do_page_lsd.click_zhangzhenbo()
        to_do_page_lsd.click_button_choose_member_ok()
        to_do_page_lsd.switch_default_frame()
        to_do_page_lsd.click_button_pass_again_ok()
        to_do_page_lsd.get_pass_result_text()
        to_do_page_lsd.click_button_pass_again_ok_known()

        # 退出登录 登陆张振博
        index_page.click_exit_to_do()
        index_page.hover_user_info()
        index_page.click_button_quit()
        home_page.input_user("jtzhangzhenbo")
        home_page.input_passwd("123456")
        home_page.submit_login()
        # 办理审签- 张振博
        index_page.hover_user_info()
        index_page.click_to_do()
        to_do_page_zzb.click_max_to_do_frame()
        to_do_page_zzb.switch_to_to_do_frame()
        to_do_page_zzb.click_button_to_do_solve()
        to_do_page_zzb.switch_default_frame()
        to_do_page_zzb.click_button_max_frame_task_detail()
        to_do_page_zzb.switch_frame_task_deal()
        to_do_page_zzb.switch_frame_task_detail()
        # to_do_page_lsd.send_keys_input_comment('ZHR-自动化测试 - 刘绍东 - 拟办意见')
        # to_do_page_lsd.click_button_signature()
        to_do_page_zzb.click_button_save()
        to_do_page_zzb.switch_default_frame()
        to_do_page_zzb.click_button_saved_known()
        to_do_page_zzb.switch_frame_task_deal()
        to_do_page_zzb.switch_frame_task_detail()
        to_do_page_zzb.click_button_pass()
        to_do_page_zzb.switch_default_frame()
        to_do_page_zzb.click_button_pass_yes()
        to_do_page_zzb.get_pass_result_text()
        to_do_page_zzb.click_button_pass_again_ok_known()
        index_page.click_exit_to_do()

        # 退出登录 登陆杨磊
        index_page.hover_user_info()
        index_page.click_button_quit()
        home_page.input_user("jtyanglei")
        home_page.input_passwd("123456")
        home_page.submit_login()
        # 文员传递 - 杨磊选归档传递给杨磊
        index_page.hover_user_info()
        index_page.click_to_do()
        todo_page_yl.click_max_to_do_frame()
        todo_page_yl.switch_to_to_do_frame()
        todo_page_yl.click_button_to_do_solve()
        todo_page_yl.switch_default_frame()
        todo_page_yl.click_button_max_frame_task_detail()
        todo_page_yl.switch_frame_task_deal()
        todo_page_yl.switch_frame_task_detail()
        # to_do_page_lsd.send_keys_input_comment('ZHR-自动化测试 - 刘绍东 - 拟办意见')
        # to_do_page_lsd.click_button_signature()
        todo_page_yl.click_button_save()
        todo_page_yl.switch_default_frame()
        todo_page_yl.click_button_saved_known()
        todo_page_yl.switch_frame_task_deal()
        todo_page_yl.switch_frame_task_detail()
        todo_page_yl.move_page_down()
        todo_page_yl.move_page_up()
        todo_page_yl.click_button_pass()
        todo_page_yl.switch_default_frame()
        todo_page_yl.switch_to_choose_member_frame()
        # todo_page_yl.move_jindutiao_down()
        todo_page_yl.click_yanglei()
        todo_page_yl.click_button_choose_member_ok()
        todo_page_yl.switch_default_frame()
        todo_page_yl.click_button_pass_again_ok()
        todo_page_yl.get_pass_result_text()
        todo_page_yl.click_button_pass_again_ok_known()
        index_page.click_exit_to_do()

        # 归档
        index_page.hover_user_info()
        index_page.click_to_do()
        todo_page_yl.click_max_to_do_frame()
        todo_page_yl.switch_to_to_do_frame()
        todo_page_yl.click_button_to_do_solve()
        todo_page_yl.switch_default_frame()
        todo_page_yl.click_button_max_frame_task_detail()
        todo_page_yl.switch_frame_task_deal()
        todo_page_yl.switch_frame_task_detail()
        todo_page_yl.click_button_on_file()
        todo_page_yl.switch_default_frame()
        todo_page_yl.click_button_on_file_yes()
        todo_page_yl.click_button_on_file_known()
        index_page.click_exit_to_do()
        index_page.hover_user_info()
        index_page.click_button_quit()


if __name__ == '__main__':
    unittest.main()
